spring:
  datasource:
    password: root00
    username: root
    url: 'jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5Dialect'

